version: "3.9"

services:
  frontend:
    build: ./fe-streamlit
    ports:
      - "8501:8501"
    command: streamlit run app.py --server.address=0.0.0.0
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=db+postgresql://user:password@database:5432/alpha
    depends_on:
      - api

  api:
    build: ./api
    ports:
      - "8000:8000"
    command: gunicorn -k uvicorn.workers.UvicornWorker --worker-connections=4000 --workers=4 -b 0.0.0.0:8000 main:app
    volumes:
      - ./api:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=db+postgresql://user:password@database:5432/alpha
    depends_on:
      - redis
      - database

  worker:
    build: ./api
    command: celery -A tasks worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./api:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=db+postgresql://user:password@database:5432/alpha
    depends_on:
      - api
      - redis
      - database

  redis:
    image: redis:latest

  database:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=alpha
    ports:
      - "5432:5432"
    user: postgres

volumes:
  postgres_data:


